<?php
// One-time admin reset script.
// Deploy and open once, then DELETE this file.
require_once __DIR__ . '/includes/init.php';

$email = 'admin@tekvion.ae';
$passwordHash = '$2y$10$Sf/BE8SH5g/FyZvrMcYySOGDQn2Te4mWZ8vy84wjJ3RLuqIDx8/n.'; // generated by assistant
try {
    $st = $pdo->prepare('INSERT INTO users (email, password_hash, name, created_at, updated_at) VALUES (?, ?, ?, NOW(), NOW()) ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), name = VALUES(name), updated_at = NOW()');
    $st->execute([$email, $passwordHash, 'Admin']);
    echo "Success: admin user created/updated for {$email}.\n";
    echo "Login with password: admin@2026 and delete this file immediately.\n";
} catch (Exception $e) {
    echo "Error: " . htmlspecialchars($e->getMessage()) . "\n";
}
